### ISSUE TITLE
feat : Order Service API

### ISSUE THREAD

**Issue by niireymik** [DEV-TINO/Festino-Admin-BE#109]
admin Order에서 서비스 주문을 넣을 수 있는 API 필요
-> OrderDAO에 isService 필드 추가 필요

**Tasks**
- [x] 학과별 Order `isService` 필드 추가
- [x] 학과별 Cook `isService` 필드 추가
- [x] Cook 생성 시 isService 정보 Order에서 받아 저장하도록 수정
- [x] 통계 조회 API : 서비스에 해당하는 Cook은 제외하고 통계 내도록 수정
- [x] 서비스 주문 추가 API 구현
