### ISSUE TITLE
fix : add `finishAt` field

### ISSUE THREAD

**Issue by niireymik** [DEV-TINO/Festino-Admin-BE#118]
주문의 조리 완료 시각을 관리하기 위해 `finishAt` 필드를 추가, 조리 완료 시 finishAt 값 설정하도록 수정

**Tasks**
- [x] 학과별 OrderDAO 및 fromOrderDTO 메서드에 `finishAt` 필드 추가
- [x] OrderDTO 및 학과별 fromOrderDAO 메서드에 `finishAt` 필드 추가
- [x] Order 조리 완료 시 `finishAt` 값 설정하도록 수정
- [x] 조리완료 주문조회 시 response에 `finishAt` 포함하도록 수정
- [x] 상세 주문조회 시 response에 `finishAt` 포함하도록 수정
