### ISSUE TITLE
Fix : ClubShow DTO

### ISSUE THREAD

**Issue by niireymik** [DEV-TINO/Festino-Admin-BE#16]
동아리 공연(타임테이블) API의 응답 DTO에서 수정사항 생김, 반영 필요

- 동아리 공연 조회 및 전체조회 응답 시 createAt과 updateAt 모두 필요 없으므로 제거하도록
- 동아리 공연 조회 및 전체조회 응답 시 현재 공연 중인지 여부를 나타내는 isShowing을 추가하도록

### Tasks
- [x] 동아리 공연 조회 Response에서 createAt, updateAt 제거
- [x] 동아리 공연 전체  조회 Response에서 createAt, updateAt 제거
- [x] 동아리 공연 조회 Response에서 isShowing 추가
- [x] 동아리 공연 전체 조회 Response에서 isShowing 추가
