### ISSUE TITLE
Fix : Reservation

### ISSUE THREAD

**Issue by 6suhyeon** [DEV-TINO/Festino-Admin-BE#57]
예약, 삭제 두 가지 종류였던 isCancel이 예약, 삭제, 완료 세 가지 타입으로 늘어나 Enum을 통해 reservationType을 생성

## Tasks

- [x] isCancel 필드 삭제하고 Enum reservationType 추가
- [x] 예약 삭제시 isCancel을 reservationType으로 변경
- [x] 예약 복구시 isCancel을 reservationType으로 변경
- [x] 예약 완료가 생김에 따라 예약 완료 API 추가
- [x] 예약 완료 목록 API 추가
